version: "3"

services:
  # web:
  #   build: .
  #   container_name: fastAPI
  #   ports:
  #     - 8000:8000
  #   environment:
  #     MYSQL_HOST: mysqldb
  #     MYSQL_PORT: 3306
  #     REDIS_HOST: redisdb
  #     REDIS_PORT: 6379
  #   volumes:
  #     - .:/demo

  pgvector:
    container_name: pgvector-2
    image: ankane/pgvector:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - ./healthfirstai_prototype/init_db/init.sql:/docker-entrypoint-initdb.d/init.sql


  # redisdb:
  #   container_name: redisdb-2
  #   image: redis/redis-stack-server:latest
  #   ports:
  #     - 6379:6379
