version: "3"

services:
  # api:
  #   build: .
  #   container_name: fastapi-healthfirstai
  #   ports:
  #     - 8000:8000
  #   environment:
  #     POSTGRES_HOST: pgvector
  #     POSTGRES_PORT: 5432
  #     REDIS_HOST: redisdb
  #     REDIS_PORT: 6379
  #   volumes:
  #     - .:/app

  pgvector:
    container_name: pgvector-healthfirstai
    image: ankane/pgvector:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    volumes:
      - ./healthfirstai_prototype/db:/docker-entrypoint-initdb.d

  redisdb:
    container_name: redisdb-healthfirstai
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
