version: "3"

services:
  # web:
  #   build: .
  #   container_name: fastAPI
  #   ports:
  #     - 8000:8000
  #   environment:
  #     MYSQL_HOST: mysqldb
  #     MYSQL_PORT: 3306
  #     REDIS_HOST: redisdb
  #     REDIS_PORT: 6379
  #   volumes:
  #     - .:/demo

  mysqldb:
    container_name: mysqldb-2
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  mysqldb:
    container_name: mysqldb-2
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: lens
  # volumes:
  #   - ./knn3_nl_to_sql/init_db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # redisdb:
  #   container_name: redisdb-2
  #   image: redis/redis-stack-server:latest
  #   ports:
  #     - 6379:6379
#   mongo:
#     image: mongo
#     restart: always
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: root
#     volumes:
#       - dbdata6:/data/db
# volumes:
#   dbdata6:
