site_name: HealthFirst AI

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# FIXME: Update the documentation so that it points to the right files
nav:
  - Getting Started: index.md
  - Agents:
      - Nutrition Agent: nutrition-agent-reference.md
      - Exercise Agent: exercise-agent-reference.md
  - Chains:
      - Advice Chain: advice-chain-reference.md
      - Diet Plan Chain: diet-plan-chain-reference.md
  - Toolkits:
      - Nutrition Tools: nutrition-tools-reference.md
      - Exercise Tools: exercise-tools-reference.md
  - Agent Feature Logic:
      - Nutrition Feature Logic: nutrition-feature-logic.md
      - Exercise Feature Logic: exercise-feature-logic.md
      - Advice Feature Logic: exercise-feature-logic.md
  - Utilities:
      - Utility Functions: util-functions-reference.md
      - Utility Models: utils-models-reference.md
  - Extract, Transform, Load (ETL):
      - Nutrition Vector Operations: nutrition-vector-ops-reference.md
  - Command Line Interface: cli.md
  - Todos: todo.md
